@extends('layouts.admin')
@section('title','Dashboard quản trị - SmashZone')
@section('page_heading','Dashboard quản trị')
@push('styles')
<style>
.dashboard-head{display:flex;align-items:end;justify-content:space-between;gap:20px;margin-bottom:22px}.date-filter{display:flex;align-items:end;gap:9px;padding:10px;border:1px solid #dfe8e4;border-radius:13px;background:#fff}.date-filter label{display:block;margin:0 0 4px;color:#75878e;font-size:9px;font-weight:900;text-transform:uppercase}.date-filter input{height:35px;border:1px solid #dce5e1;border-radius:8px;padding:0 9px;font-size:11px}.date-filter button{height:35px;border:0;border-radius:8px;background:#092f40;color:#fff;padding:0 13px;font-size:11px;font-weight:800}.kpi-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:15px;margin-bottom:20px}.kpi{position:relative;overflow:hidden;padding:19px;border:1px solid #dfe8e4;border-radius:15px;background:#fff;box-shadow:0 7px 24px rgba(22,57,51,.04)}.kpi-top{display:flex;justify-content:space-between}.kpi-icon{display:grid;place-items:center;width:40px;height:40px;border-radius:11px;background:#e4f8ee;color:#04a65f;font-size:18px}.kpi-label{color:#788a91;font-size:11px;font-weight:800}.kpi strong{display:block;margin-top:12px;font-size:27px;line-height:1;font-weight:800}.kpi small{display:block;margin-top:7px;color:#94a0a5;font-size:10px}.kpi.revenue{grid-column:span 2;background:linear-gradient(135deg,#092d3f,#075d50);color:#fff}.kpi.revenue .kpi-label,.kpi.revenue small{color:#b8d0d2}.kpi.revenue .kpi-icon{background:rgba(50,234,145,.15);color:#51ef9f}.kpi.occupancy .kpi-icon{background:#fff0da;color:#cd7500}.dashboard-charts{display:grid;grid-template-columns:1.55fr 1fr;gap:20px}.admin-card{border:1px solid #dfe8e4;border-radius:16px;background:#fff;box-shadow:0 8px 25px rgba(22,57,51,.04)}.admin-card-head{display:flex;justify-content:space-between;padding:19px 21px;border-bottom:1px solid #edf2ef}.admin-card-head h2{margin:0;font-size:15px;font-weight:800}.admin-card-head span{color:#829198;font-size:10px}.chart-wrap{height:310px;padding:18px}.popular-item{display:grid;grid-template-columns:31px 1fr auto;gap:11px;align-items:center;padding:14px 20px;border-bottom:1px solid #edf2ef}.popular-item:last-child{border:0}.popular-rank{display:grid;place-items:center;width:29px;height:29px;border-radius:9px;background:#e7f8ef;color:#049d5b;font-size:11px;font-weight:900}.popular-item strong,.popular-item small{display:block}.popular-item strong{font-size:12px}.popular-item small{margin-top:3px;color:#87969b;font-size:10px}.popular-count{color:#0a9d5e;font-size:17px;font-weight:900}.popular-count small{color:#8a999e;text-align:right;font-size:9px;font-weight:700}@media(max-width:1100px){.kpi-grid{grid-template-columns:repeat(2,1fr)}.dashboard-charts{grid-template-columns:1fr}}@media(max-width:650px){.dashboard-head{align-items:stretch;flex-direction:column}.date-filter{display:grid;grid-template-columns:1fr 1fr}.date-filter button{grid-column:span 2}.kpi-grid{grid-template-columns:1fr}.kpi.revenue{grid-column:auto}}
</style>
@endpush
@section('content')
<div class="dashboard-head"><div class="admin-page-title"><h1>Tổng quan kinh doanh</h1><p>Dữ liệu thực tế từ {{ $from->format('d/m/Y') }} đến {{ $to->format('d/m/Y') }}</p></div><form class="date-filter" method="GET"><div><label>Từ ngày</label><input name="from" type="date" value="{{ $from->toDateString() }}"></div><div><label>Đến ngày</label><input name="to" type="date" value="{{ $to->toDateString() }}"></div><button><i class="bi bi-funnel me-1"></i>Áp dụng</button></form></div>
<section class="kpi-grid"><article class="kpi"><div class="kpi-top"><span class="kpi-label">TỔNG SÂN</span><i class="kpi-icon bi bi-grid-3x3-gap"></i></div><strong>{{ number_format($kpis['courts']) }}</strong><small>Toàn hệ thống</small></article><article class="kpi"><div class="kpi-top"><span class="kpi-label">KHÁCH HÀNG</span><i class="kpi-icon bi bi-people"></i></div><strong>{{ number_format($kpis['customers']) }}</strong><small>Tài khoản khách hàng</small></article><article class="kpi"><div class="kpi-top"><span class="kpi-label">BOOKING</span><i class="kpi-icon bi bi-calendar2-check"></i></div><strong>{{ number_format($kpis['bookings']) }}</strong><small>Trong kỳ thống kê</small></article><article class="kpi occupancy"><div class="kpi-top"><span class="kpi-label">TỶ LỆ LẤP ĐẦY</span><i class="kpi-icon bi bi-pie-chart"></i></div><strong>{{ $kpis['occupancy_rate'] }}%</strong><small>Trên tổng công suất</small></article><article class="kpi revenue"><div class="kpi-top"><span class="kpi-label">DOANH THU</span><i class="kpi-icon bi bi-cash-stack"></i></div><strong>{{ number_format($kpis['revenue']) }}đ</strong><small>Thanh toán thành công trong kỳ</small></article><article class="kpi"><div class="kpi-top"><span class="kpi-label">BOOKING CHỜ</span><i class="kpi-icon bi bi-hourglass-split"></i></div><strong>{{ number_format($kpis['pending']) }}</strong><small>Chờ thanh toán</small></article><article class="kpi"><div class="kpi-top"><span class="kpi-label">HOÀN THÀNH</span><i class="kpi-icon bi bi-check2-circle"></i></div><strong>{{ number_format($kpis['completed']) }}</strong><small>Đã hoàn thành</small></article></section>
<div class="dashboard-charts"><section class="admin-card"><header class="admin-card-head"><h2>Booking & doanh thu theo ngày</h2><span>{{ $from->format('d/m') }} – {{ $to->format('d/m/Y') }}</span></header><div class="chart-wrap"><canvas id="performanceChart"></canvas></div></section><section class="admin-card"><header class="admin-card-head"><h2>Sân được đặt nhiều</h2><span>TOP 5</span></header>@foreach($popularCourts as $court)<div class="popular-item"><span class="popular-rank">{{ $loop->iteration }}</span><div><strong>{{ $court->name }}</strong><small>{{ $court->courtType->name }} · {{ $court->code }}</small></div><div class="popular-count">{{ $court->booking_count }}<small>lượt đặt</small></div></div>@endforeach</section></div>
@endsection
@push('scripts')<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js"></script><script>const chartData=@json($chart);new Chart(document.getElementById('performanceChart'),{type:'bar',data:{labels:chartData.labels,datasets:[{label:'Booking',data:chartData.bookings,backgroundColor:'#25d984',borderRadius:5,yAxisID:'y'},{label:'Doanh thu',data:chartData.revenue,type:'line',borderColor:'#0a5266',backgroundColor:'rgba(10,82,102,.1)',tension:.35,pointRadius:2,yAxisID:'revenue'}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom',labels:{boxWidth:10,font:{size:10}}}},scales:{x:{grid:{display:false},ticks:{font:{size:9},maxTicksLimit:12}},y:{beginAtZero:true,ticks:{precision:0,font:{size:9}}},revenue:{position:'right',beginAtZero:true,grid:{display:false},ticks:{font:{size:9},callback:v=>new Intl.NumberFormat('vi-VN',{notation:'compact'}).format(v)+'đ'}}}}});</script>@endpush
