@extends('layouts.app')
@section('title', $court->name.' — SmashZone')
@section('body_class', 'sz-courts-page')
@push('styles') @vite(['resources/css/courts.css', 'resources/js/courts.js']) @endpush
@section('content')
<x-booking-progress :step="2"/>
@php
    $minimumPrice = $court->prices->min('price');
    $images = $court->images;
    $canBook = !auth()->check() || (auth()->user()->role ?: 'CUSTOMER') === 'CUSTOMER';
@endphp
<section class="court-gallery" aria-label="Hình ảnh sân">
    @if($images->isNotEmpty())<a class="court-gallery-main" href="{{ $images->first()->url }}" target="_blank" rel="noopener" aria-label="Mở ảnh sân kích thước lớn"><img id="court-main-image" src="{{ $images->first()->url }}" alt="{{ $court->name }}" width="1200" height="600" fetchpriority="high"></a><div class="court-gallery-thumbs">@foreach($images as $image)<button type="button" data-gallery-image="{{ $image->url }}" aria-label="Xem ảnh {{ $loop->iteration }} của {{ $court->name }}" aria-pressed="{{ $loop->first ? 'true' : 'false' }}"><img src="{{ $image->url }}" alt="" width="160" height="110" loading="lazy"></button>@endforeach</div>@else<x-empty-state icon="bi-image" title="Hình ảnh đang được cập nhật" description="Thông tin sân và lịch đặt vẫn được hiển thị bên dưới."/>@endif
</section>
<header class="court-page-heading"><nav aria-label="Đường dẫn"><a href="{{ route('home') }}">Trang chủ</a><span>/</span><a href="{{ route('courts.index') }}">Sân cầu lông</a><span>/</span><span>{{ $court->name }}</span></nav><span class="court-eyebrow">{{ $court->courtType?->name }}</span><h1>{{ $court->name }}</h1><div class="court-detail-meta"><span><i class="bi bi-geo-alt" aria-hidden="true"></i> {{ $court->address ?: 'Địa chỉ đang cập nhật' }}</span><span class="court-rating"><i class="bi bi-star-fill" aria-hidden="true"></i> {{ $rating_stats->total ? number_format($rating_stats->average, 1).' / 5 · '.$rating_stats->total.' đánh giá' : 'Chưa có đánh giá' }}</span><x-status-badge label="Đang hoạt động" tone="success"/></div></header>
<div class="court-detail-layout">
    <div class="court-detail-content">
        <nav class="court-section-nav" aria-label="Thông tin sân"><a href="#about-court">Giới thiệu</a><a href="#court-amenities">Tiện ích</a><a href="#court-policy">Chính sách</a><a href="#court-reviews">Đánh giá</a><a href="#booking-card">Đặt sân</a></nav>
        <section class="card court-info-section" id="about-court"><div class="card-body"><h2>Về {{ $court->name }}</h2><p class="court-description">{{ $court->description ?: 'Mô tả sân đang được cập nhật.' }}</p><div class="court-contact-details">@if($court->opening_time && $court->closing_time)<span><i class="bi bi-clock" aria-hidden="true"></i> {{ substr($court->opening_time, 0, 5) }} – {{ substr($court->closing_time, 0, 5) }}</span>@endif @if($court->phone)<span><i class="bi bi-telephone" aria-hidden="true"></i> {{ $court->phone }}</span>@endif</div></div></section>
        <section class="card court-info-section" id="court-amenities"><div class="card-body"><h2>Tiện ích tại sân</h2><div class="court-amenity-list">@forelse($court->amenities as $amenity)<div><i class="bi bi-check2-circle" aria-hidden="true"></i><span>{{ $amenity->name }}</span></div>@empty<p class="text-muted mb-0">Tiện ích đang được cập nhật.</p>@endforelse</div></div></section>
        <section class="card court-info-section" id="court-schedule"><div class="card-body"><div class="court-schedule-heading"><div><h2>Chọn khung giờ</h2><p class="text-muted mb-0">Lịch ngày {{ $selectedDate->format('d/m/Y') }} · Chọn các khung giờ liền nhau.</p></div></div>
            <div class="court-slot-legend"><x-status-badge label="Còn trống" tone="success"/><x-status-badge label="Đã đặt" tone="danger"/><x-status-badge label="Đang giữ" tone="warning"/><x-status-badge label="Không khả dụng"/></div>
            <div id="slot-message" class="alert alert-warning" role="status" hidden></div>
            <div class="court-slot-grid" data-slot-grid>
            @foreach($scheduleCourts as $scheduleCourt) @foreach($timeSlots as $slot)
                @php
                    $item = $scheduleAvailability[$scheduleCourt->id][$slot->id] ?? ['status' => null, 'price' => 0];
                    $isAvailable = $item['status'] === 'AVAILABLE' && $item['price'] > 0;
                    $slotLabel = match($item['status']) { 'AVAILABLE' => $isAvailable ? 'Còn trống' : 'Chưa có giá', 'BOOKED' => 'Đã đặt', 'HOLD' => 'Đang giữ', default => 'Không khả dụng' };
                    $slotTone = match($item['status']) { 'AVAILABLE' => $isAvailable ? 'available' : 'locked', 'BOOKED' => 'booked', 'HOLD' => 'held', default => 'locked' };
                @endphp
                <button type="button" class="court-slot cell {{ $slotTone }}" data-court="{{ $scheduleCourt->id }}" data-slot="{{ $slot->id }}" data-start="{{ substr($slot->start_time, 0, 5) }}" data-end="{{ substr($slot->end_time, 0, 5) }}" data-price="{{ $item['price'] }}" aria-pressed="false" @disabled(!$isAvailable)><strong>{{ substr($slot->start_time, 0, 5) }} – {{ substr($slot->end_time, 0, 5) }}</strong><span data-slot-label>{{ $slotLabel }}</span>@if($isAvailable)<small>{{ number_format($item['price'], 0, ',', '.') }}đ</small>@endif</button>
            @endforeach @endforeach
            </div>@if($timeSlots->isEmpty())<x-empty-state title="Chưa có khung giờ" description="Lịch sân đang được cập nhật."/>@endif
        </div></section>
        <section class="card court-info-section" id="court-policy"><div class="card-body"><h2>Chính sách đặt sân</h2><ul class="court-policy-list"><li>Đặt trước tối đa {{ config('booking.max_days', 30) }} ngày.</li><li>Chọn các khung giờ liên tiếp trên cùng một sân cho mỗi lượt đặt.</li><li>Khung giờ được giữ trong {{ config('booking.hold_timeout', 5) }} phút khi tạo đơn chờ thanh toán.</li><li>Giá và mã khuyến mãi được hệ thống kiểm tra khi xác nhận đặt sân.</li></ul><a href="{{ route('contacts.index') }}">Liên hệ nếu bạn cần hỗ trợ <i class="bi bi-arrow-up-right" aria-hidden="true"></i></a></div></section>
        <section class="card court-info-section" id="court-reviews"><div class="card-body"><h2>Đánh giá khách hàng <span class="text-muted">({{ $rating_stats->total }})</span></h2>@forelse($reviews as $review)<article class="court-review"><div><strong>{{ $review->user?->name ?? 'Khách hàng' }}</strong><time datetime="{{ $review->created_at->toDateString() }}">{{ $review->created_at->format('d/m/Y') }}</time></div><p class="court-rating" aria-label="{{ $review->rating }} trên 5 sao">@for($star=1; $star<=5; $star++)<i class="bi {{ $star <= $review->rating ? 'bi-star-fill' : 'bi-star' }}" aria-hidden="true"></i>@endfor</p><p>{{ $review->content }}</p>@if($review->images->isNotEmpty())<div class="court-review-images">@foreach($review->images as $reviewImage)@php($reviewUrl = Str::startsWith($reviewImage->image, ['http://','https://','/']) ? $reviewImage->image : asset('storage/'.$reviewImage->image))<a href="{{ $reviewUrl }}" target="_blank" rel="noopener"><img src="{{ $reviewUrl }}" alt="Ảnh đánh giá sân" loading="lazy" width="100" height="80"></a>@endforeach</div>@endif</article>@empty<x-empty-state icon="bi-chat-square-heart" title="Chưa có đánh giá" description="Các đánh giá được duyệt sẽ xuất hiện tại đây."/>@endforelse<div class="mt-3">{{ $reviews->appends(['booking_date' => $selectedDate->toDateString()])->fragment('court-reviews')->links() }}</div></div></section>
    </div>
    <aside class="court-booking-card card" id="booking-card" aria-labelledby="booking-heading"><div class="card-body"><span class="court-eyebrow">LÊN LỊCH TRẬN ĐẤU</span><h2 id="booking-heading">Đặt sân của bạn</h2><div class="court-booking-price">@if($minimumPrice !== null)<strong>{{ number_format($minimumPrice, 0, ',', '.') }}đ</strong><span> / giờ · giá từ</span>@else<span>Giá sân đang cập nhật</span>@endif</div>
        <form action="{{ route('courts.show', $court) }}#court-schedule" method="GET" data-date-form><label class="form-label" for="dateInput">Ngày chơi</label><div class="court-date-controls"><input class="form-control" type="date" id="dateInput" name="booking_date" value="{{ $selectedDate->toDateString() }}" min="{{ today()->toDateString() }}" max="{{ today()->addDays(config('booking.max_days', 30))->toDateString() }}" required><button class="btn btn-outline-primary" type="submit">Xem lịch</button></div></form>
        <div data-date-loading hidden><x-loading-state label="Đang tải lịch sân…"/></div>
        <div class="court-selected-summary"><span class="form-label">Khung giờ <span id="selectionCount">0</span></span><p id="selected-time-label" aria-live="polite">Chưa chọn khung giờ.</p><a href="#court-schedule">Chọn khung giờ <i class="bi bi-arrow-up-right" aria-hidden="true"></i></a></div>
        @include('partials.booking-service-picker')
        <form id="bookingForm" action="{{ route('bookings.store') }}" method="POST" data-court-booking data-court-id="{{ $court->id }}" data-initial-slots="{{ json_encode(old('time_slot_ids', request('time_slot_id') ? [(int) request('time_slot_id')] : [])) }}">@csrf<input type="hidden" name="court_id" id="courtId" value=""><input type="hidden" name="booking_date" value="{{ $selectedDate->toDateString() }}"><span id="selectedSlots"></span><label class="form-label" for="voucher_code">Khuyến mãi</label><input class="form-control" id="voucher_code" name="voucher_code" value="{{ old('voucher_code') }}" maxlength="50" placeholder="Nhập mã khuyến mãi" aria-describedby="voucher-help"><p class="form-text" id="voucher-help">Mã được kiểm tra khi xác nhận. Giảm giá chưa được áp dụng vào tạm tính.</p>
            @if($canBook)<button id="court-voucher-apply" class="btn btn-outline-primary btn-sm" type="submit" disabled>Áp dụng &amp; tiếp tục</button><p class="form-text">Áp dụng mã khi tạo đơn giữ chỗ, rồi kiểm tra tổng tiền tại checkout.</p>@endif
            @error('voucher_code')<p class="text-danger small" role="alert">{{ $message }}</p>@enderror
            <div class="court-totals" aria-live="polite"><div><span>Tiền sân</span><strong id="court-cost">0đ</strong></div><div><span>Dịch vụ</span><strong id="services-cost">0đ</strong></div><div><span>Tạm tính</span><strong id="subtotal-cost">0đ</strong></div><div><span>Giảm giá</span><span id="discount-label">Chưa áp dụng</span></div><div class="court-total"><span>Tổng tiền dự kiến</span><strong id="selectionSummary">0đ</strong></div></div>
            @if(session('booking_errors'))<div class="alert alert-danger">{{ collect(session('booking_errors'))->pluck('message')->implode('; ') }}</div>@endif
            @if($canBook)<button id="court-submit" class="btn btn-primary w-100" type="submit" disabled>@auth Xác nhận đặt sân @else Đăng nhập để đặt sân @endauth <i class="bi bi-arrow-right" aria-hidden="true"></i></button>@else<p class="alert alert-info">Đặt sân trực tuyến dành cho tài khoản khách hàng.</p>@endif
            <p class="court-checkout-note">Tình trạng sân và tổng tiền được xác nhận lại khi tạo đơn.</p>
        </form>
        <a class="court-recurring-link" href="{{ route('bookings.create-recurring', ['court_id' => $court->id]) }}">Bạn muốn đặt sân định kỳ?</a>
    </div></aside>
</div>
@endsection
