<!doctype html>
<html lang="vi">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Đặt sân · {{ $court->name }}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet">
    <style>
        :root{--green:#08dc6b;--ink:#081527;--muted:#58708b;--line:#d8e0da;--page:#f5faf1;--empty:#edf1ef;--selected:#ffc20e;--booked:#ee6868}*{box-sizing:border-box}body{margin:0;color:var(--ink);background:var(--page);font:14px Inter,Arial,sans-serif}button,input{font:inherit}a{color:inherit;text-decoration:none}
        .topbar{height:83px;display:flex;align-items:center;padding:0 clamp(20px,6.5vw,126px);border-top:1px solid var(--line);border-bottom:1px solid var(--line);background:#fff}.back{display:flex;align-items:center;gap:29px;font-size:22px;font-weight:800;letter-spacing:-.5px}.back i{font-size:20px;font-weight:400}.help{margin-left:auto;font-size:19px}.booking-page{min-height:calc(100vh - 83px)}
        .date-area{padding:28px 20px 50px;overflow:hidden}.date-head{max-width:1880px;margin:0 auto 12px;display:flex;justify-content:space-between;align-items:center;color:var(--green);font-size:17px;font-weight:800}.date-picker{border:0;background:none;color:var(--green);font-size:14px;font-weight:700;cursor:pointer}.date-picker i{margin-right:8px;font-size:18px;vertical-align:-1px}.native-date-picker{position:absolute;width:1px;height:1px;opacity:0;pointer-events:none}.dates{max-width:1880px;margin:auto;display:flex;gap:10px;overflow-x:auto;padding-bottom:4px;scrollbar-width:thin}.day{flex:0 0 80px;height:100px;padding:12px 6px 9px;display:flex;flex-direction:column;align-items:center;justify-content:space-between;border:1px solid var(--line);border-radius:15px;background:#fff}.day:hover{border-color:#8fceaa}.day small{color:#52708d;font-size:12px;font-weight:700;text-transform:uppercase}.day strong{font-size:23px;line-height:1}.day em{color:#8392a1;font-size:12px;font-style:normal}.day.selected{border-color:var(--green);background:var(--green);color:#fff;box-shadow:0 5px 12px #08dc6b2e}.day.selected small,.day.selected em{color:#fff}
        .schedule-title{max-width:1920px;margin:auto;padding:0 20px 64px}.schedule-title h1{margin:0 0 10px;font-size:23px;letter-spacing:-.6px}.schedule-title p{margin:0;color:var(--muted);font-size:16px}.notice{max-width:1880px;margin:0 auto 16px;padding:12px 15px;color:#b42318;border-radius:8px;background:#feecec}.board{border-top:1px solid var(--line);border-bottom:1px solid var(--line);background:#fff}.board-controls{height:60px;padding:0 22px;display:flex;align-items:center;justify-content:flex-end;gap:13px;color:var(--muted)}.board-controls input{width:120px;accent-color:var(--green)}.board-controls small{min-width:38px}
        .scroll{min-height:300px;max-height:calc(100vh - 410px);overflow:auto}.scroll.single-court{min-height:0}.timetable{--slot-width:100px;min-width:max-content;display:grid;grid-template-columns:120px repeat(var(--slots),var(--slot-width));border-top:1px solid var(--line)}.timetable>*{border-right:1px solid var(--line);border-bottom:1px solid var(--line)}.corner{position:sticky;left:0;z-index:4;display:flex;align-items:center;justify-content:center;min-height:59px;background:#fff;color:#637a92;font-size:13px;font-weight:700}.time{position:relative;display:flex;align-items:flex-end;justify-content:center;min-height:59px;padding:0 4px 10px;color:#52708d;font-size:12px;font-weight:800}.time:before{content:"";position:absolute;top:10px;width:2px;height:20px;background:#d5ddd5}.court-name{position:sticky;left:0;z-index:3;display:flex;align-items:center;min-height:80px;padding-left:39px;background:#fff;font-weight:700}.cell{min-height:80px;border:0;border-right:1px solid var(--line);border-bottom:1px solid var(--line);background:var(--empty);color:#aeb9b1;font-size:14px;font-weight:800;cursor:not-allowed}.cell.available{background:#f1fbed;color:var(--green);cursor:pointer}.cell.available:hover{background:#def8e4}.cell.selected{background:var(--selected);color:#5c4400}.cell.booked{background:var(--booked);color:#fff}.cell:disabled{opacity:1}
        .legend{display:flex;align-items:center;gap:25px;flex-wrap:wrap;padding:21px 40px;color:#58708b;background:var(--page);font-size:16px}.legend span{display:flex;align-items:center;gap:8px}.legend i{width:20px;height:20px;display:inline-block;border-radius:5px}.legend .selected{background:var(--selected)}.legend .available{border:1px solid #d5e1d7;background:#f8fcf4}.legend .booked{background:var(--booked)}.legend .locked{background:var(--empty)}
        .selection-bar{position:fixed;right:0;bottom:0;left:0;z-index:10;display:none;align-items:center;justify-content:space-between;padding:20px clamp(24px,5.5vw,105px);border-top:1px solid var(--line);background:rgba(255,255,255,.97);box-shadow:0 -8px 28px rgba(8,21,39,.07);backdrop-filter:blur(10px)}.selection-bar.visible{display:flex}.selection-details{display:flex;flex-direction:column;align-items:flex-start;gap:10px}.selection-cart{display:inline-flex;align-items:center;gap:9px;padding:8px 14px;border:1px solid #a7efc5;border-radius:8px;background:#effdf4;color:#00c963;font-size:17px;font-weight:700}.selection-cart i{font-size:19px}.selection-cart b{display:grid;min-width:24px;height:24px;place-items:center;border-radius:50%;background:var(--green);color:#fff;font-size:13px}.selection-total{color:var(--green);font-size:29px;line-height:1;font-weight:800;letter-spacing:.2px}.continue{display:inline-flex;align-items:center;gap:18px;border:0;border-radius:16px;padding:22px 31px;background:var(--green);color:#fff;font-size:20px;font-weight:800;cursor:pointer;box-shadow:0 9px 19px rgba(8,220,107,.25)}.continue i{font-size:21px}.continue:hover{background:#00c963}
        @media(max-width:700px){.topbar{height:64px;padding:0 18px}.back{gap:14px;font-size:17px}.date-area{padding:20px 14px 30px}.schedule-title{padding:0 14px 34px}.schedule-title p{font-size:14px}.board-controls{height:45px}.timetable{grid-template-columns:92px repeat(var(--slots),82px)}.court-name{padding-left:15px}.legend{gap:14px;padding:16px;font-size:14px}.scroll{max-height:calc(100vh - 360px)}.selection-bar{padding:14px 18px}.selection-details{gap:6px}.selection-cart{padding:6px 10px;font-size:13px}.selection-cart i{font-size:15px}.selection-cart b{min-width:20px;height:20px;font-size:11px}.selection-total{font-size:20px}.continue{gap:10px;border-radius:12px;padding:15px 18px;font-size:16px}.continue i{font-size:17px}}
        .calendar-modal{position:fixed;inset:0;z-index:100;display:none;align-items:center;justify-content:center;padding:20px;background:rgba(8,21,39,.56)}.calendar-modal.open{display:flex}.calendar-dialog{width:min(448px,100%);padding:24px;border-radius:16px;background:#fff;box-shadow:0 24px 60px rgba(8,21,39,.3)}.calendar-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:22px}.calendar-head strong{font-size:18px;text-transform:capitalize}.calendar-nav{width:38px;height:38px;border:0;border-radius:50%;background:#edf8ed;color:#008c4d;font-size:23px;cursor:pointer}.calendar-weekdays,.calendar-grid{display:grid;grid-template-columns:repeat(7,1fr);gap:7px;text-align:center}.calendar-weekdays{margin-bottom:9px;color:#71818a;font-size:12px}.calendar-day{height:43px;border:0;border-radius:10px;background:transparent;color:var(--ink);font-weight:600;cursor:pointer}.calendar-day:hover:not(:disabled){background:#e8f9f1}.calendar-day.selected{background:#008c4d;color:#fff}.calendar-day:disabled{color:#c4cbc7;cursor:not-allowed}.calendar-foot{display:flex;justify-content:flex-end;gap:12px;margin-top:22px}.calendar-cancel,.calendar-confirm{border:0;border-radius:8px;padding:10px 17px;font-weight:700;cursor:pointer}.calendar-cancel{background:transparent;color:#008c4d}.calendar-confirm{background:#008c4d;color:#fff}
    </style>
</head>
<body>
    <header class="topbar"><a class="back" href="{{ route('courts.index') }}"><i class="bi bi-chevron-left"></i><span>{{ $court->name }}</span></a><i class="bi bi-info-circle help" title="Hướng dẫn đặt sân"></i></header>
    <div class="calendar-modal" id="calendarModal" aria-hidden="true"><div class="calendar-dialog" role="dialog" aria-modal="true" aria-label="Chọn ngày đặt sân"><div class="calendar-head"><button class="calendar-nav" id="calendarPrev" type="button" aria-label="Tháng trước">‹</button><strong id="calendarTitle"></strong><button class="calendar-nav" id="calendarNext" type="button" aria-label="Tháng sau">›</button></div><div class="calendar-weekdays"><span>T2</span><span>T3</span><span>T4</span><span>T5</span><span>T6</span><span>T7</span><span>CN</span></div><div class="calendar-grid" id="calendarGrid"></div><div class="calendar-foot"><button class="calendar-cancel" id="calendarCancel" type="button">Hủy</button><button class="calendar-confirm" id="calendarConfirm" type="button">Xác nhận</button></div></div></div>
    <main class="booking-page">
        <section class="date-area"><div class="date-head"><span>Tháng {{ $selectedDate->month }}, {{ $selectedDate->year }}</span><button class="date-picker" type="button" id="openDatePicker"><i class="bi bi-calendar4-week"></i>Chọn ngày</button><input class="native-date-picker" id="dateInput" type="date" min="{{ now()->toDateString() }}" max="{{ now()->addDays(config('booking.max_days', 30))->toDateString() }}" value="{{ $selectedDate->toDateString() }}" aria-label="Chọn ngày đặt sân"></div><nav class="dates" aria-label="Chọn ngày">@foreach($dateRange as $date)<a class="day {{ $date->isSameDay($selectedDate) ? 'selected' : '' }}" href="{{ route('courts.show', $court) }}?booking_date={{ $date->toDateString() }}"><small>{{ ['CN','Thứ 2','Thứ 3','Thứ 4','Thứ 5','Thứ 6','Thứ 7'][$date->dayOfWeek] }}</small><strong>{{ $date->day }}</strong><em>T{{ $date->month }}</em></a>@endforeach</nav></section>
        <section class="schedule-title"><h1>Lịch sân cầu lông</h1><p>Chọn khung giờ còn trống để đặt sân. Vui lòng chọn các khung giờ liên tiếp theo quy định của sân.</p></section>
        @if($errors->any() || session('error'))<div class="notice">{{ session('error') ?: $errors->first() }}</div>@endif
        <section class="board"><div class="board-controls"><i class="bi bi-zoom-out"></i><input id="zoom" type="range" min="72" max="150" value="100" aria-label="Phóng to lịch"><i class="bi bi-zoom-in"></i><small id="zoomText">100%</small></div><div class="scroll {{ $scheduleCourts->count() === 1 ? 'single-court' : '' }}"><div class="timetable" id="timetable" style="--slots:{{ $timeSlots->count() }}"><div class="corner">Sân</div>@foreach($timeSlots as $slot)<div class="time">{{ \Carbon\Carbon::parse($slot->start_time)->format('H:i') }}</div>@endforeach
        @foreach($scheduleCourts as $scheduleCourt)<div class="court-name">{{ $scheduleCourt->name }}</div>@foreach($timeSlots as $slot)@php($item = $scheduleAvailability[$scheduleCourt->id][$slot->id] ?? ['status'=>'MAINTENANCE','price'=>0])@php($isAvailable = $item['status'] === 'AVAILABLE' && $item['price'] > 0)<button type="button" class="cell {{ $isAvailable ? 'available' : ($item['status'] === 'BOOKED' ? 'booked' : '') }}" data-court="{{ $scheduleCourt->id }}" data-slot="{{ $slot->id }}" data-price="{{ $item['price'] }}" {{ $isAvailable ? '' : 'disabled' }}>{{ $isAvailable ? number_format($item['price'] / 1000, 0).'k' : '' }}</button>@endforeach @endforeach
        </div></div><div class="legend"><span><i class="selected"></i>Đã chọn</span><span><i class="available"></i>Trống</span><span><i class="booked"></i>Đã đặt</span><span><i class="locked"></i>Khóa</span></div></section>
    </main>
    <form id="bookingForm" method="POST" action="{{ route('bookings.store') }}">@csrf<input type="hidden" name="court_id" id="courtId"><input type="hidden" name="booking_date" value="{{ $selectedDate->toDateString() }}"><span id="selectedSlots"></span></form><aside class="selection-bar" id="selectionBar"><span id="selectionSummary"></span><button class="continue" type="submit" form="bookingForm">@auth Tiếp tục @else Đăng nhập để đặt @endauth</button></aside>
    <script>
        const bar=document.getElementById('selectionBar');
        bar.innerHTML='<div class="selection-details"><span class="selection-cart"><i class="bi bi-cart3"></i> Giỏ hàng <b id="selectionCount">0</b></span><strong class="selection-total" id="selectionSummary">0đ</strong></div><button class="continue" type="submit" form="bookingForm">Tiếp tục <i class="bi bi-chevron-right"></i></button>';
        const selected=new Map(),slotsField=document.getElementById('selectedSlots'),courtId=document.getElementById('courtId'),summary=document.getElementById('selectionSummary'),selectedCount=document.getElementById('selectionCount');
        document.querySelectorAll('.cell.available').forEach(cell=>cell.addEventListener('click',()=>setTimeout(()=>{const total=[...selected.values()].reduce((sum,value)=>sum+value,0);selectedCount.textContent=selected.size;summary.textContent=`${total.toLocaleString('vi-VN')} đ`;})));
        const dateInput=document.getElementById('dateInput'),calendarModal=document.getElementById('calendarModal'),calendarGrid=document.getElementById('calendarGrid'),calendarTitle=document.getElementById('calendarTitle');let pickedDate=dateInput.value,calendarMonth=new Date(`${pickedDate}T00:00:00`);calendarMonth.setDate(1);const dateCode=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`,minDate=dateInput.min,maxDate=dateInput.max;
        function renderCalendar(){const year=calendarMonth.getFullYear(),month=calendarMonth.getMonth(),days=new Date(year,month+1,0).getDate(),offset=(new Date(year,month,1).getDay()+6)%7;calendarTitle.textContent=calendarMonth.toLocaleDateString('vi-VN',{month:'long',year:'numeric'});calendarGrid.innerHTML='';for(let i=0;i<offset;i++)calendarGrid.insertAdjacentHTML('beforeend','<span></span>');for(let day=1;day<=days;day++){const date=new Date(year,month,day),value=dateCode(date),disabled=value<minDate||value>maxDate;calendarGrid.insertAdjacentHTML('beforeend',`<button type="button" class="calendar-day ${value===pickedDate?'selected':''}" data-date="${value}" ${disabled?'disabled':''}>${day}</button>`)}calendarGrid.querySelectorAll('.calendar-day:not(:disabled)').forEach(button=>button.addEventListener('click',()=>{pickedDate=button.dataset.date;renderCalendar()}));}
        function closeCalendar(){calendarModal.classList.remove('open');calendarModal.setAttribute('aria-hidden','true');document.body.style.overflow=''}document.getElementById('openDatePicker').addEventListener('click',()=>{pickedDate=dateInput.value;calendarMonth=new Date(`${pickedDate}T00:00:00`);calendarMonth.setDate(1);renderCalendar();calendarModal.classList.add('open');calendarModal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'});document.getElementById('calendarPrev').addEventListener('click',()=>{calendarMonth.setMonth(calendarMonth.getMonth()-1);renderCalendar()});document.getElementById('calendarNext').addEventListener('click',()=>{calendarMonth.setMonth(calendarMonth.getMonth()+1);renderCalendar()});document.getElementById('calendarCancel').addEventListener('click',closeCalendar);document.getElementById('calendarConfirm').addEventListener('click',()=>{location.href='{{ route('courts.show', $court) }}?booking_date='+pickedDate});calendarModal.addEventListener('click',event=>{if(event.target===calendarModal)closeCalendar()});document.addEventListener('keydown',event=>{if(event.key==='Escape')closeCalendar()});document.getElementById('zoom').addEventListener('input',e=>{document.getElementById('timetable').style.setProperty('--slot-width',e.target.value+'px');document.getElementById('zoomText').textContent=e.target.value+'%'});
        document.querySelectorAll('.cell.available').forEach(cell=>cell.addEventListener('click',()=>{const currentCourt=cell.dataset.court;if(selected.size&&courtId.value!==currentCourt){alert('Vui lòng chỉ chọn khung giờ của một sân trong mỗi lượt đặt.');return}if(selected.has(cell.dataset.slot)){selected.delete(cell.dataset.slot);cell.classList.remove('selected')}else{selected.set(cell.dataset.slot,Number(cell.dataset.price));cell.classList.add('selected');courtId.value=currentCourt}if(!selected.size)courtId.value='';slotsField.innerHTML=[...selected.keys()].map(id=>`<input type="hidden" name="time_slot_ids[]" value="${id}">`).join('');const total=[...selected.values()].reduce((sum,value)=>sum+value,0);summary.textContent=`${selected.size} khung giờ · ${total.toLocaleString('vi-VN')}đ`;bar.classList.toggle('visible',selected.size>0)}));
    </script>
</body>
</html>
