@extends('layouts.admin')
@section('page_heading','Vai trò & quyền')
@section('content')<x-admin.workspace>
<div class="d-flex justify-content-between align-items-center mb-4"><div><x-admin.page-heading>Vai trò nhân viên</x-admin.page-heading><p class="text-muted mb-0">Nhóm quyền thao tác và gán cho nhân viên tại Quản lý người dùng.</p></div><button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#role-new">+ Thêm mới</button></div>
<div class="table-responsive"><table class="table"><thead><tr><th>Vai trò</th><th>Quyền được cấp</th><th>Thao tác</th></tr></thead><tbody>@forelse($roles as $role)<tr><td><strong>{{ $role->name }}</strong></td><td>{{ collect($role->permissions ?? [])->map(fn($key)=>$permissions[$key] ?? $key)->join(', ') ?: 'Chưa cấp quyền' }}</td><td><x-admin.row-actions><button type="button" data-bs-toggle="modal" data-bs-target="#role-{{ $role->id }}">Sửa</button><form method="POST" action="{{ route('admin.roles.destroy',$role) }}">@csrf @method('DELETE')<button class="text-danger">Xóa</button></form></x-admin.row-actions></td></tr>@empty<tr><td colspan="3"><x-admin.empty /></td></tr>@endforelse</tbody></table></div>
@foreach($roles->concat([new \App\Models\AccessRole]) as $role)
<div class="modal fade" id="role-{{ $role->id ?? 'new' }}" tabindex="-1" aria-labelledby="role-title-{{ $role->id ?? 'new' }}" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h2 class="modal-title fs-5" id="role-title-{{ $role->id ?? 'new' }}">{{ $role->exists?'Sửa vai trò':'Thêm vai trò' }}</h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Đóng"></button></div><div class="modal-body"><form method="POST" action="{{ $role->exists?route('admin.roles.update',$role):route('admin.roles.store') }}">@csrf<input type="hidden" name="_ui_form" value="role-{{ $role->id ?? 'new' }}"> @if($role->exists) @method('PUT') @endif<label class="form-label d-block">Tên vai trò<input class="form-control" name="name" value="{{ old('_ui_form') === 'role-'.($role->id ?? 'new') ? old('name', $role->name) : $role->name }}" maxlength="100" required></label><div class="row mt-3">@foreach($permissions as $key=>$label)<label class="col-md-6 mb-2"><input class="form-check-input" type="checkbox" name="permissions[]" value="{{ $key }}" @checked(in_array($key, old('_ui_form') === 'role-'.($role->id ?? 'new') ? old('permissions',[]) : ($role->permissions??[])))> {{ $label }}</label>@endforeach</div><p class="small text-muted mt-3">Admin có toàn quyền. Quyền của khách hàng giữ nguyên theo hệ thống.</p><button class="btn btn-primary mt-2">Lưu vai trò</button></form></div></div></div></div>
@endforeach
</x-admin.workspace>@endsection
