@extends('layouts.admin')
@section('page_heading','Thông tin tài khoản')
@section('content')<x-admin.workspace>
<a href="{{ route('admin.users.index') }}">← Danh sách người dùng</a><x-admin.page-heading>{{ $account->exists?'Sửa':'Thêm' }} tài khoản</x-admin.page-heading>
<form class="card card-body" method="POST" action="{{ $account->exists ? route('admin.users.update',$account) : route('admin.users.store') }}">@csrf @if($account->exists) @method('PUT') @endif
@foreach(['name'=>'Họ tên','email'=>'Email','phone'=>'Số điện thoại','password'=>'Mật khẩu','password_confirmation'=>'Nhập lại mật khẩu'] as $key=>$label)<label class="form-label">{{ $label }} @if($key==='password' && $account->exists)(để trống để giữ nguyên)@endif</label><input class="form-control mb-3" name="{{ $key }}" type="{{ str_starts_with($key,'password')?'password':($key==='email'?'email':'text') }}" value="{{ str_starts_with($key,'password')?'':old($key,$account->$key) }}" @if(in_array($key,['name','email'])) required @endif>@endforeach
@foreach(['role'=>['ADMIN'=>'Admin','EMPLOYEE'=>'Nhân viên','CUSTOMER'=>'Khách hàng'],'status'=>['ACTIVE'=>'Hoạt động','LOCKED'=>'Đã khóa'],'customer_segment'=>['NEW'=>'Khách mới','REGULAR'=>'Khách thường','VIP'=>'Khách VIP']] as $key=>$options)<label class="form-label">{{ ['role'=>'Vai trò hệ thống','status'=>'Trạng thái','customer_segment'=>'Phân loại khách hàng'][$key] }}</label><select class="form-select mb-3" name="{{ $key }}">@foreach($options as $value=>$label)<option value="{{ $value }}" @selected(old($key,$account->$key ?? ($key==='role'?'CUSTOMER':array_key_first($options)))===$value)>{{ $label }}</option>@endforeach</select>@endforeach
<label class="form-label">Vai trò nhân viên</label><select class="form-select mb-3" name="access_role_id"><option value="">Không gán</option>@foreach($roles as $role)<option value="{{ $role->id }}" @selected(old('access_role_id',$account->access_role_id)==$role->id)>{{ $role->name }}</option>@endforeach</select>
<p>Quyền bổ sung (chỉ áp dụng cho nhân viên)</p><div class="row">@foreach($permissions as $key=>$label)<label class="col-md-6 mb-2"><input type="checkbox" name="permissions[]" value="{{ $key }}" @checked(in_array($key,old('permissions',$account->permissions??[])))> {{ $label }}</label>@endforeach</div><button class="btn btn-success align-self-start mt-3">Lưu tài khoản</button></form>
</x-admin.workspace>@endsection
