@extends('layouts.admin')
@section('page_heading','Notification Center')
@push('styles')<style>.nc-grid{display:grid;grid-template-columns:390px 1fr;gap:20px}.nc-card{border:1px solid #e0e8e4;border-radius:16px;background:#fff;box-shadow:0 8px 25px rgba(8,38,53,.05)}.nc-form{padding:22px}.nc-form h3{font-size:18px;font-weight:850}.nc-form label{display:block;margin:13px 0 5px;font-size:10px;font-weight:900;color:#64748b}.nc-form input,.nc-form textarea,.nc-form select{width:100%;padding:10px;border:1px solid #dce5e1;border-radius:9px;font-size:12px}.nc-form select[multiple]{height:140px}.nc-btn{border:0;border-radius:9px;padding:11px 15px;background:#0ea36b;color:#fff;font-weight:800}.nc-filter{display:flex;gap:8px;padding:16px}.nc-filter input,.nc-filter select{padding:9px;border:1px solid #dce5e1;border-radius:8px}.nc-table{width:100%;font-size:11px}.nc-table th,.nc-table td{padding:13px;border-top:1px solid #edf2ef;vertical-align:top}.nc-table th{color:#64748b}.nc-metric{font-weight:850;color:#0b8a5a}.nc-bar{height:5px;margin-top:5px;border-radius:9px;background:#e8efec;overflow:hidden}.nc-bar i{display:block;height:100%;background:#0ea36b}.target-box{display:none}.target-box.show{display:block}.nc-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:18px}.nc-stat{padding:15px}.nc-stat strong{display:block;font-size:22px}.nc-stat span{font-size:11px;color:#718087}@media(max-width:1050px){.nc-grid{grid-template-columns:1fr}.nc-summary{grid-template-columns:1fr}}</style>@endpush
@section('content')
@php
    $campaigns = $announcements->getCollection();
    $totalSent = $campaigns->sum('sent_count'); $totalRead = $campaigns->sum('read_count'); $totalClicked = $campaigns->sum('clicked_count');
@endphp
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="nc-summary"><div class="nc-card nc-stat"><span>ĐÃ GỬI (TRANG NÀY)</span><strong>{{ number_format($totalSent) }}</strong></div><div class="nc-card nc-stat"><span>TỶ LỆ ĐỌC</span><strong>{{ $totalSent ? round($totalRead/$totalSent*100,1) : 0 }}%</strong></div><div class="nc-card nc-stat"><span>CTR</span><strong>{{ $totalSent ? round($totalClicked/$totalSent*100,1) : 0 }}%</strong></div></div>
<div class="nc-grid">
<section class="nc-card nc-form"><h3>📢 Tạo chiến dịch thông báo</h3><form method="POST" action="{{ route('admin.announcements.store') }}">@csrf
<label>TIÊU ĐỀ</label><input name="title" value="{{ old('title') }}" required maxlength="255">
<label>NỘI DUNG</label><textarea name="content" rows="5" required maxlength="5000">{{ old('content') }}</textarea>
<label>LIÊN KẾT KHI BẤM “XEM”</label><input name="action_url" value="{{ old('action_url','/') }}" placeholder="Ví dụ: /booking hoặc /#offers">
<label>NHÓM TÀI KHOẢN</label><select name="audience"><option value="CUSTOMER">Khách hàng</option><option value="ALL">Tất cả tài khoản</option><option value="EMPLOYEE">Nhân viên / Admin</option></select>
<label>CÁCH CHỌN NGƯỜI NHẬN</label><select name="target_type" id="target-type"><option value="AUDIENCE">Toàn bộ nhóm trên</option><option value="SELECTED">Chọn khách hàng</option><option value="COURT">Khách từng đặt theo sân</option><option value="AREA">Khách từng đặt theo khu vực</option></select>
<div class="target-box" data-target="SELECTED"><label>KHÁCH HÀNG</label><select name="target_user_ids[]" multiple>@foreach($customers as $customer)<option value="{{ $customer->id }}">{{ $customer->name }} · {{ $customer->email }}</option>@endforeach</select><small>Giữ Ctrl để chọn nhiều khách.</small></div>
<div class="target-box" data-target="COURT"><label>SÂN</label><select name="court_id"><option value="">-- Chọn sân --</option>@foreach($courts as $court)<option value="{{ $court->id }}">{{ $court->name }}</option>@endforeach</select></div>
<div class="target-box" data-target="AREA"><label>KHU VỰC / ĐỊA CHỈ SÂN</label><select name="area"><option value="">-- Chọn khu vực --</option>@foreach($areas as $area)<option value="{{ $area }}">{{ $area }}</option>@endforeach</select></div>
<label>THỜI GIAN GỬI <small>(để trống = gửi ngay)</small></label><input type="datetime-local" name="scheduled_at" value="{{ old('scheduled_at') }}">
<button class="nc-btn mt-3">Gửi / Lên lịch</button></form></section>
<section><div class="nc-card"><form class="nc-filter"><input name="search" value="{{ request('search') }}" placeholder="Tìm tiêu đề..."><select name="status"><option value="">Mọi trạng thái</option>@foreach(['DRAFT','SCHEDULED','SENT','CANCELLED'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ $status }}</option>@endforeach</select><button class="nc-btn">Lọc</button></form><div class="table-responsive"><table class="nc-table"><thead><tr><th>Chiến dịch</th><th>Đối tượng</th><th>Trạng thái</th><th>Đã gửi</th><th>Đã đọc</th><th>CTR</th><th></th></tr></thead><tbody>
@forelse($announcements as $a)@php($readRate=$a->sent_count?round($a->read_count/$a->sent_count*100,1):0)@php($ctr=$a->sent_count?round($a->clicked_count/$a->sent_count*100,1):0)<tr><td><strong>{{ $a->title }}</strong><br><small>{{ Str::limit($a->content,70) }}</small><br><small>{{ $a->sent_at?->format('d/m/Y H:i') ?? ($a->scheduled_at?->format('d/m/Y H:i') ?: 'Chưa gửi') }}</small></td><td>{{ $a->target_type }}@if($a->court)<br>{{ $a->court->name }}@elseif($a->area)<br>{{ Str::limit($a->area,35) }}@endif</td><td>{{ $a->status }}</td><td class="nc-metric">{{ $a->sent_count }}</td><td><span class="nc-metric">{{ $a->read_count }} · {{ $readRate }}%</span><div class="nc-bar"><i style="width:{{ $readRate }}%"></i></div><small>Chưa đọc: {{ max(0,$a->sent_count-$a->read_count) }}</small></td><td class="nc-metric">{{ $a->clicked_count }} · {{ $ctr }}%</td><td>@if($a->status!=='SENT')<form method="POST" action="{{ route('admin.announcements.destroy',$a) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Xóa</button></form>@endif</td></tr>@empty<tr><td colspan="7" class="text-center py-4">Chưa có chiến dịch.</td></tr>@endforelse
</tbody></table></div></div><div class="mt-3">{{ $announcements->links() }}</div></section>
</div>
<script>const targetType=document.getElementById('target-type');function syncTarget(){document.querySelectorAll('.target-box').forEach(box=>box.classList.toggle('show',box.dataset.target===targetType.value))}targetType.addEventListener('change',syncTarget);syncTarget();</script>
@endsection
