@extends('layouts.admin')
@section('page_heading','Khung giờ')
@section('content')<x-admin.workspace>
<div class="d-flex justify-content-between align-items-center mb-4"><div><x-admin.page-heading>Khung giờ</x-admin.page-heading><p class="text-muted mb-0">Cấu hình thời gian chơi và trạng thái sử dụng.</p></div><a class="btn btn-primary" href="{{ route('admin.pricing.index') }}"><i class="bi bi-plus-lg"></i> Thêm mới</a></div>
<x-admin.filters><input class="form-control" name="search" value="{{ request('search') }}" placeholder="Tìm khung giờ"><select class="form-select" name="status" aria-label="Trạng thái"><option value="">Mọi trạng thái</option>@foreach(['ACTIVE'=>'Hoạt động','INACTIVE'=>'Ngừng hoạt động'] as $code=>$text)<option value="{{ $code }}" @selected(request('status')===$code)>{{ $text }}</option>@endforeach</select><button class="btn btn-primary">Lọc</button></x-admin.filters>
<div class="table-responsive"><table class="table"><thead><tr><th>Khung giờ</th><th>Thời gian</th><th>Thời lượng</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>
@forelse($slots as $slot)<tr><td>{{ $slot->name }}</td><td>{{ substr($slot->start_time,0,5) }} – {{ substr($slot->end_time,0,5) }}</td><td>{{ $slot->duration }} phút</td><td><span class="badge bg-light text-dark">{{ $slot->status }}</span></td><td><x-admin.row-actions><button type="button" data-bs-toggle="modal" data-bs-target="#slot-edit-{{ $slot->id }}"><i class="bi bi-pencil"></i>Sửa</button><form method="POST" action="{{ route('admin.slots.toggle',$slot) }}">@csrf @method('PUT')<button>{{ $slot->status==='ACTIVE'?'Ngừng hoạt động':'Kích hoạt' }}</button></form><form method="POST" action="{{ route('admin.pricing.slots.destroy',$slot) }}">@csrf @method('DELETE')<button class="text-danger">Xóa</button></form></x-admin.row-actions></td></tr>@empty<tr><td colspan="5"><x-admin.empty /></td></tr>@endforelse
</tbody></table></div><x-admin.pagination :rows="$slots" />
@foreach($slots as $slot)<div class="modal fade" id="slot-edit-{{ $slot->id }}" tabindex="-1" aria-labelledby="slot-title-{{ $slot->id }}" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h2 id="slot-title-{{ $slot->id }}" class="modal-title fs-5">Sửa {{ $slot->name }}</h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Đóng"></button></div><form method="POST" action="{{ route('admin.pricing.slots.update',$slot) }}" class="modal-body">@csrf<input type="hidden" name="_ui_form" value="slot-edit-{{ $slot->id }}"> @method('PUT')
<label class="form-label d-block">Tên khung giờ<input class="form-control" name="name" value="{{ old('_ui_form') === 'slot-edit-'.$slot->id ? old('name', $slot->name) : $slot->name }}" required></label><div class="row g-3"><label class="col-6">Bắt đầu<input class="form-control" type="time" name="start_time" value="{{ old('_ui_form') === 'slot-edit-'.$slot->id ? old('start_time', substr($slot->start_time,0,5)) : substr($slot->start_time,0,5) }}" required></label><label class="col-6">Kết thúc<input class="form-control" type="time" name="end_time" value="{{ old('_ui_form') === 'slot-edit-'.$slot->id ? old('end_time', substr($slot->end_time,0,5)) : substr($slot->end_time,0,5) }}" required></label></div><label class="form-label d-block mt-3">Số phút<input class="form-control" type="number" name="duration" value="{{ old('_ui_form') === 'slot-edit-'.$slot->id ? old('duration', $slot->duration) : $slot->duration }}" min="1" required></label><button class="btn btn-primary mt-2">Lưu thay đổi</button></form></div></div></div>@endforeach
</x-admin.workspace>@endsection
