@extends('layouts.employee')
@section('title','Xử lý đơn '.$booking->booking_code)
@section('page_heading','Chi tiết đơn đặt sân')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-3"><div><h2 class="mb-1">{{ $booking->booking_code }}</h2><span class="staff-badge">{{ $booking->status }}</span></div><a href="{{ route('employee.bookings.index') }}" class="staff-button">Quay lại</a></div>
<div class="row g-3"><div class="col-lg-7"><div class="staff-card p-4 mb-3"><h5>Khách hàng & lịch chơi</h5><p><strong>{{ $booking->user->name }}</strong> · {{ $booking->user->phone }} · {{ $booking->user->email }}</p>@foreach($booking->bookingDetails as $d)<div class="border-top py-2">{{ $d->court->name }} — {{ $d->booking_date->format('d/m/Y') }} — {{ substr($d->timeSlot->start_time,0,5) }}–{{ substr($d->timeSlot->end_time,0,5) }}</div>@endforeach</div>
<div class="staff-card p-4"><h5>Dịch vụ phát sinh</h5><table class="table"><tbody>@foreach($booking->services as $service)<tr><td>{{ $service->item->name }}</td><td>{{ $service->quantity }} × {{ number_format($service->unit_price) }}đ</td><td>{{ number_format($service->subtotal) }}đ</td><td>@if($booking->status==='CHECKED_IN' && auth()->user()->hasPermission('services.manage'))<form method="POST" action="{{ route('employee.bookings.services.destroy',[$booking,$service]) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Xóa</button></form>@endif</td></tr>@endforeach</tbody></table>@if($booking->status==='CHECKED_IN' && auth()->user()->hasPermission('services.manage'))<form method="POST" action="{{ route('employee.bookings.services.store',$booking) }}" class="row g-2">@csrf<div class="col-7"><select name="service_item_id" class="form-select" required><option value="">Chọn dịch vụ</option>@foreach($serviceItems as $item)<option value="{{ $item->id }}">{{ $item->name }} — {{ number_format($item->price) }}đ</option>@endforeach</select></div><div class="col-2"><input type="number" name="quantity" value="1" min="1" class="form-control"></div><div class="col-3"><button class="staff-button staff-button-primary w-100 justify-content-center">Thêm</button></div></form>@endif</div></div>
<div class="col-lg-5"><div class="staff-card p-4 mb-3"><h5>Thanh toán</h5><div class="display-6 fw-bold mb-3">{{ number_format($booking->total_amount) }}đ</div><p>Trạng thái: <strong>{{ $booking->payment_status }}</strong></p>@if($booking->payment_status!=='PAID' && auth()->user()->hasPermission('payments.counter'))<form method="POST" action="{{ route('employee.bookings.payment',$booking) }}">@csrf<select name="payment_method" class="form-select mb-2" required><option value="CASH">Tiền mặt</option><option value="BANK_TRANSFER">Chuyển khoản</option><option value="QR">QR Code</option></select><input name="amount" type="number" value="{{ (float)$booking->total_amount }}" class="form-control mb-2" required><input name="transaction_id" class="form-control mb-2" placeholder="Mã giao dịch (nếu có)"><button class="staff-button staff-button-primary w-100 justify-content-center">Xác nhận thanh toán</button></form>@endif</div>
<div class="staff-card p-4"><h5>Thao tác vận hành</h5>@if($booking->status==='CONFIRMED' && auth()->user()->hasPermission('bookings.checkin'))<form method="POST" action="{{ route('employee.bookings.check-in',$booking) }}">@csrf<button class="staff-button staff-button-primary w-100 justify-content-center">Check-in khách hàng</button></form>@elseif($booking->status==='CHECKED_IN' && auth()->user()->hasPermission('bookings.checkout'))<form method="POST" action="{{ route('employee.bookings.complete',$booking) }}">@csrf<button class="staff-button staff-button-primary w-100 justify-content-center">Hoàn thành lượt chơi</button></form>@else<p class="text-muted mb-0">Không có thao tác phù hợp ở trạng thái hiện tại.</p>@endif</div></div></div>
@endsection
