@extends('layouts.employee')
@section('page_heading', 'Thiết bị / đồ thuê')
@section('content')
@php($labels = ['AVAILABLE'=>'Sẵn sàng','ON_LOAN'=>'Đang mượn','DAMAGED'=>'Hỏng','LOST'=>'Mất'])
<h1 class="h3 mb-4">Thiết bị và mượn / trả</h1>
<div class="row g-4"><div class="col-lg-6"><form method="POST" action="{{ route('employee.equipment.store') }}" class="staff-card p-4">@csrf<h2 class="h5">Thêm thiết bị</h2><label class="form-label">Mã thiết bị<input name="code" class="form-control" required maxlength="100"></label><label class="form-label d-block">Tên thiết bị<input name="name" class="form-control" required></label><label class="form-label d-block">Tình trạng ban đầu<textarea name="condition_note" class="form-control" required></textarea></label><button class="staff-button">Thêm thiết bị</button></form></div>
<div class="col-lg-6"><form method="POST" action="{{ route('employee.equipment.lend') }}" class="staff-card p-4">@csrf<h2 class="h5">Ghi nhận cho mượn</h2><label class="form-label d-block">Thiết bị<select name="equipment_id" class="form-select" required>@foreach($equipment->where('status','AVAILABLE') as $item)<option value="{{ $item->id }}">{{ $item->code }} — {{ $item->name }}</option>@endforeach</select></label><label class="form-label d-block">Mã booking đang check-in<input name="booking_code" class="form-control" required></label><label class="form-label d-block">Kiểm tra tình trạng khi giao<textarea name="issue_note" class="form-control" required></textarea></label><button class="staff-button staff-button-primary">Xác nhận cho mượn</button></form></div></div>
<h2 class="h5 mt-4">Danh sách thiết bị</h2><div class="staff-card table-responsive"><table class="table staff-table"><thead><tr><th>Thiết bị</th><th>Trạng thái</th><th>Ghi chú</th><th>Kiểm tra lại</th></tr></thead><tbody>@forelse($equipment as $item)<tr><td>{{ $item->code }} · {{ $item->name }}</td><td>{{ $labels[$item->status] }}</td><td>{{ $item->condition_note }}</td><td>@if(in_array($item->status,['DAMAGED','LOST']))<form method="POST" action="{{ route('employee.equipment.restore',$item) }}">@csrf<input name="condition_note" aria-label="Kết quả kiểm tra" placeholder="Đã sửa / tìm lại, tình trạng..." class="form-control mb-2" required><button class="staff-button">Đưa vào sử dụng</button></form>@endif</td></tr>@empty<tr><td colspan="4">Chưa có thiết bị.</td></tr>@endforelse</tbody></table></div>
<h2 class="h5 mt-4">Lịch sử mượn / trả</h2>@forelse($loans as $loan)<div class="staff-card p-3 mb-3"><strong>{{ $loan->equipment->name }} · {{ $loan->booking->booking_code }} · {{ $loan->booking->user->name }}</strong><p>Giao {{ $loan->created_at->format('d/m/Y H:i') }}: {{ $loan->issue_note }}</p>@if($loan->returned_at)<p class="mb-0">{{ $loan->returned_at->format('d/m/Y H:i') }} · {{ $labels[$loan->return_status] }} · {{ $loan->return_note }}</p>@else<form method="POST" action="{{ route('employee.equipment.return',$loan) }}" class="d-flex flex-wrap gap-2">@csrf<select name="return_status" class="form-select w-auto" aria-label="Tình trạng trả"><option value="AVAILABLE">Trả nguyên vẹn</option><option value="DAMAGED">Báo hỏng</option><option value="LOST">Báo mất</option></select><input name="return_note" placeholder="Kết quả kiểm tra / mô tả hỏng mất" aria-label="Ghi chú trả" class="form-control" required><button class="staff-button">Xác nhận trả / báo cáo</button></form>@endif</div>@empty<p>Chưa có lượt mượn.</p>@endforelse{{ $loans->links() }}
@endsection
