@extends('layouts.admin')
@section('title', 'Thanh toán - SmashZone')
@section('page_heading', 'Thanh toán')
@section('content')<x-admin.workspace>
<div class="d-flex justify-content-between align-items-end mb-4"><div><x-admin.page-heading>Giao dịch thanh toán</x-admin.page-heading><p class="text-muted mb-0">Đối chiếu booking và xử lý giao dịch lỗi.</p></div><x-admin.filters class="d-flex gap-2"><input class="form-control" name="search" value="{{ request('search') }}" placeholder="Mã giao dịch / booking"><select class="form-select" name="status"><option value="">Mọi trạng thái</option>@foreach(['PENDING','PAID','FAILED'] as $status)<option @selected(request('status') === $status)>{{ $status }}</option>@endforeach</select><select class="form-select" name="refund_status"><option value="">Mọi trạng thái hoàn</option>@foreach(['NONE'=>'Chưa hoàn','PARTIALLY_REFUNDED'=>'Hoàn một phần','REFUNDED'=>'Hoàn toàn bộ'] as $code=>$label)<option value="{{ $code }}" @selected(request('refund_status') === $code)>{{ $label }}</option>@endforeach</select><button class="btn btn-dark"><i class="bi bi-search"></i></button></x-admin.filters></div>
<div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Giao dịch</th><th>Booking / khách</th><th>Số tiền</th><th>Trạng thái</th><th>Thời gian</th><th></th></tr></thead><tbody>
@forelse($payments as $payment)<tr><td><strong>{{ $payment->transaction_id ?: 'Chưa có mã' }}</strong><br><small>{{ $payment->purpose === 'SERVICE' ? 'Dịch vụ phát sinh' : 'Tiền đặt sân' }}</small></td><td><strong>{{ ($payment->fixedBooking?->code ?? $payment->booking?->booking_code) }}</strong><br><small>{{ ($payment->fixedBooking?->user ?? $payment->booking?->user)?->name }}</small></td><td>{{ number_format($payment->amount) }}đ</td><td>{{ $payment->status }}</td><td>{{ $payment->created_at->format('d/m/Y H:i') }}</td><td><x-admin.row-actions><a class="btn btn-sm btn-outline-secondary" href="{{ route('admin.payments.show', $payment) }}"><i class="bi bi-eye"></i></a></x-admin.row-actions></td></tr>@empty<tr><td colspan="6" class="text-center py-5 text-muted"><x-admin.empty message="Không tìm thấy giao dịch." /></td></tr>@endforelse
</tbody></table></div></div><div class="mt-3"><x-admin.pagination :rows="$payments" /></div>
</x-admin.workspace>@endsection
