@extends('layouts.admin')
@section('title', 'Chi tiết giao dịch - SmashZone')
@section('page_heading', 'Chi tiết giao dịch')
@section('content')
@if($payment->purpose === 'SERVICE')<p class="badge text-bg-primary">Thanh toán dịch vụ riêng</p>@endif
<div class="alert alert-light border">Giao dịch thu: <strong>{{ $payment->status }}</strong> · Tiền gốc: {{ number_format($payment->amount) }}đ · Đã hoàn: {{ number_format($payment->refunded_amount) }}đ · Trạng thái hoàn: {{ $payment->refund_status }}</div>
<a href="{{ route('admin.payments.index') }}">← Danh sách giao dịch</a><h1 class="h3 fw-bold my-3">{{ $payment->transaction_id ?: 'Giao dịch #'.$payment->id }}</h1>
<div class="row g-4"><div class="col-lg-7"><section class="card border-0 shadow-sm p-4 mb-4"><h2 class="h5">Thông tin giao dịch</h2><dl class="row mb-0"><dt class="col-4">Booking</dt><dd class="col-8">{{ ($payment->fixedBooking?->code ?? $payment->booking?->booking_code) }}</dd><dt class="col-4">Khách hàng</dt><dd class="col-8">{{ ($payment->fixedBooking?->user ?? $payment->booking?->user)?->name }} · {{ ($payment->fixedBooking?->user ?? $payment->booking?->user)?->email }}</dd><dt class="col-4">Số tiền</dt><dd class="col-8">{{ number_format($payment->amount) }}đ</dd><dt class="col-4">Trạng thái</dt><dd class="col-8">{{ $payment->status }}</dd></dl></section>
<section class="card border-0 shadow-sm p-4"><h2 class="h5">Lịch sử giao dịch</h2>@forelse($payment->transactionLogs->sortByDesc('created_at') as $log)<div class="border-bottom py-2"><strong>{{ $log->action }} · {{ $log->actor?->name }}</strong><small class="d-block text-muted">{{ $log->old_status }} → {{ $log->new_status }} · {{ number_format($log->amount) }}đ · {{ $log->created_at->format('d/m/Y H:i:s') }}</small><div>{{ $log->note }}</div></div>@empty<p class="text-muted">Chưa có lịch sử.</p>@endforelse</section></div>
<div class="col-lg-5"><section class="card border-0 shadow-sm p-4"><h2 class="h5">Đối chiếu giao dịch</h2><form method="POST" action="{{ route('admin.payments.reconcile', $payment) }}">@csrf @method('PUT')<label class="form-label">Kết quả</label><select class="form-select mb-3" name="action"><option value="MARK_PAID">Xác nhận đã thanh toán</option><option value="MARK_FAILED">Đánh dấu thất bại</option></select><label class="form-label">Số tiền</label><input class="form-control mb-3" type="number" name="amount" value="{{ $payment->amount }}" required><label class="form-label">Mã giao dịch</label><input class="form-control mb-3" name="transaction_id" value="{{ $payment->transaction_id }}"><label class="form-label">Ghi chú</label><textarea class="form-control mb-3" name="note" required></textarea><button class="btn btn-success">Cập nhật giao dịch</button></form></section></div></div>
@endsection
