@extends('layouts.admin')
@section('title', ($employee ? 'Cập nhật' : 'Thêm').' nhân viên - SmashZone')
@section('page_heading', 'Nhân viên & phân quyền')
@section('content')<x-admin.workspace>
<div class="mb-3"><a href="{{ route('admin.employees.index') }}">← Danh sách nhân viên</a><x-admin.page-heading>{{ $employee ? 'Cập nhật nhân viên' : 'Thêm nhân viên' }}</x-admin.page-heading></div>
<form class="card border-0 shadow-sm p-4" method="POST" action="{{ $employee ? route('admin.employees.update', $employee) : route('admin.employees.store') }}">@csrf @if($employee) @method('PUT') @endif
<div class="row g-3"><div class="col-md-6"><label class="form-label">Họ và tên</label><input class="form-control" name="name" value="{{ old('name', $employee?->name) }}" required></div><div class="col-md-6"><label class="form-label">Email</label><input class="form-control" type="email" name="email" value="{{ old('email', $employee?->email) }}" required></div><div class="col-md-6"><label class="form-label">Số điện thoại</label><input class="form-control" name="phone" value="{{ old('phone', $employee?->phone) }}"></div><div class="col-md-6"><label class="form-label">Role</label><select class="form-select" name="role"><option value="EMPLOYEE" @selected(old('role', $employee?->role ?? 'EMPLOYEE') === 'EMPLOYEE')>Nhân viên</option><option value="ADMIN" @selected(old('role', $employee?->role) === 'ADMIN')>Admin</option></select></div><div class="col-md-6"><label class="form-label">Mật khẩu {{ $employee ? 'mới' : '' }}</label><input class="form-control" type="password" name="password" @required(!$employee)></div><div class="col-md-6"><label class="form-label">Xác nhận mật khẩu</label><input class="form-control" type="password" name="password_confirmation" @required(!$employee)></div></div>
<hr><h2 class="h5">Quyền nhân viên</h2><div class="row g-2">@foreach($permissionOptions as $key => $label)<div class="col-md-6"><label class="form-check"><input class="form-check-input" type="checkbox" name="permissions[]" value="{{ $key }}" @checked(in_array($key, old('permissions', $employee?->permissions ?? [])))><span class="form-check-label">{{ $label }}</span></label></div>@endforeach</div><div class="mt-4 d-flex justify-content-end gap-2"><a class="btn btn-outline-secondary" href="{{ route('admin.employees.index') }}">Hủy</a><button class="btn btn-success"><i class="bi bi-floppy me-1"></i>Lưu tài khoản</button></div></form>
@if($employee && !$employee->is(Auth::user()))<form class="mt-3" method="POST" action="{{ route('admin.employees.toggle-status', $employee) }}">@csrf @method('PUT')<button class="btn btn-outline-danger">{{ $employee->status === 'ACTIVE' ? 'Khóa tài khoản' : 'Mở khóa tài khoản' }}</button></form>@endif
</x-admin.workspace>@endsection
