@extends('layouts.admin')
@section('page_heading','Khuyến mãi')
@section('content')<x-admin.workspace>
<div class="d-flex justify-content-between align-items-center mb-4"><div><x-admin.page-heading>Khuyến mãi</x-admin.page-heading><p class="text-muted mb-0">Quản lý hiệu lực, giá trị ưu đãi và lượt sử dụng.</p></div><a class="btn btn-primary" href="{{ route('admin.vouchers.create') }}"><i class="bi bi-plus-lg"></i> Thêm mới</a></div>
<x-admin.filters><input class="form-control" name="search" value="{{ request('search') }}" placeholder="Tìm mã hoặc tên voucher" aria-label="Tìm voucher"><select class="form-select" name="status" aria-label="Trạng thái"><option value="">Mọi trạng thái</option>@foreach(['ACTIVE'=>'Hoạt động','INACTIVE'=>'Ngừng hoạt động'] as $code=>$text)<option value="{{ $code }}" @selected(request('status')===$code)>{{ $text }}</option>@endforeach</select><button class="btn btn-primary">Lọc</button></x-admin.filters>
<div class="table-responsive"><table class="table"><thead><tr><th>Voucher</th><th>Giảm giá</th><th>Hiệu lực</th><th>Đã sử dụng</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>
@forelse($vouchers as $voucher)<tr><td><strong>{{ $voucher->code }}</strong><small class="d-block text-muted">{{ $voucher->name }}</small></td><td>{{ $voucher->discount_type==='PERCENTAGE'?$voucher->discount_value.'%':number_format($voucher->discount_value,0,',','.').'đ' }}<small class="d-block text-muted">Tối thiểu {{ number_format($voucher->min_order_amount,0,',','.') }}đ</small></td><td>{{ $voucher->start_at->format('d/m/Y') }} – {{ $voucher->end_at->format('d/m/Y') }}</td><td>{{ $voucher->used_count }} / {{ $voucher->usage_limit ?? 'Không giới hạn' }}</td><td><span class="badge bg-light text-dark">{{ $voucher->status }}</span></td><td><x-admin.row-actions><a href="{{ route('admin.vouchers.edit',$voucher) }}"><i class="bi bi-pencil"></i>Sửa</a><form method="POST" action="{{ route('admin.vouchers.toggle',$voucher) }}">@csrf @method('PUT')<button><i class="bi bi-power"></i>{{ $voucher->status==='ACTIVE'?'Ngừng hoạt động':'Kích hoạt' }}</button></form><form method="POST" action="{{ route('admin.vouchers.destroy',$voucher) }}">@csrf @method('DELETE')<button class="text-danger"><i class="bi bi-trash"></i>Xóa</button></form></x-admin.row-actions></td></tr>@empty<tr><td colspan="6"><x-admin.empty /></td></tr>@endforelse
</tbody></table></div><x-admin.pagination :rows="$vouchers" />
</x-admin.workspace>@endsection
