@extends('layouts.admin')
@section('title',$knowledge->exists?'Sửa kiến thức AI':'Thêm kiến thức AI')
@section('page_heading','Knowledge Base / RAG')
@section('content')
<style>.kb-form{max-width:980px;border:0;border-radius:18px;box-shadow:0 7px 24px rgba(10,49,58,.07)}.kb-note{border-radius:14px;background:#eaf8f3;color:#24594b}</style>
<div class="mb-4"><a class="text-decoration-none text-muted" href="{{ route('admin.knowledge-base.index') }}">← Kho kiến thức</a><h1 class="h3 mt-2">{{ $knowledge->exists?'Sửa kiến thức':'Thêm kiến thức mới' }}</h1></div>
<div class="card kb-form"><div class="card-body p-4"><div class="kb-note p-3 mb-4"><strong><i class="bi bi-stars me-1"></i>Tự động RAG</strong><div class="small mt-1">Sau khi lưu, nội dung được chia chunk và tạo embedding. SmashBot có thể dùng bản cập nhật ngay mà không cần sửa code.</div></div>
<form method="POST" action="{{ $knowledge->exists?route('admin.knowledge-base.update',$knowledge):route('admin.knowledge-base.store') }}">@csrf @if($knowledge->exists) @method('PUT') @endif
<div class="row g-3"><div class="col-md-8"><label class="form-label fw-semibold">Tiêu đề</label><input class="form-control" name="title" maxlength="255" required value="{{ old('title',$knowledge->title) }}" placeholder="Ví dụ: Chính sách hủy sân"></div><div class="col-md-4"><label class="form-label fw-semibold">Danh mục</label><select class="form-select" name="category" required>@foreach($categories as $key=>$label)<option value="{{ $key }}" @selected(old('category',$knowledge->category?:'FAQ')===$key)>{{ $label }}</option>@endforeach</select></div>
<div class="col-12"><label class="form-label fw-semibold">Nội dung kiến thức</label><textarea class="form-control" name="answer" rows="14" maxlength="30000" required placeholder="Nhập nội dung chính xác mà SmashBot được phép sử dụng...">{{ old('answer',$knowledge->answer) }}</textarea><div class="form-text">Nên viết rõ điều kiện, ngoại lệ và mốc thời gian. Không đưa API key hoặc dữ liệu cá nhân vào đây.</div></div>
<div class="col-md-8"><label class="form-label fw-semibold">Từ khóa</label><input class="form-control" name="keywords_text" value="{{ old('keywords_text',collect($knowledge->keywords)->join(', ')) }}" placeholder="hủy sân, hoàn tiền, đổi lịch"></div><div class="col-md-2"><label class="form-label fw-semibold">Ưu tiên</label><input class="form-control" type="number" name="priority" min="0" max="100" value="{{ old('priority',$knowledge->priority??10) }}" required></div><div class="col-md-2 d-flex align-items-end"><div class="form-check form-switch mb-2"><input type="hidden" name="active" value="0"><input class="form-check-input" type="checkbox" name="active" value="1" id="active" @checked(old('active',$knowledge->exists?$knowledge->active:true))><label class="form-check-label" for="active">Kích hoạt</label></div></div></div>
<div class="d-flex gap-2 mt-4"><button class="btn btn-success px-4"><i class="bi bi-cloud-arrow-up me-1"></i>Lưu & đồng bộ RAG</button><a class="btn btn-outline-secondary" href="{{ route('admin.knowledge-base.index') }}">Hủy</a></div></form></div></div>
@endsection
