@extends('layouts.admin')
@section('title','Quản lý kiến thức AI')
@section('page_heading','Knowledge Base / RAG')
@section('content')
<style>.kb-card{border:0;border-radius:16px;box-shadow:0 7px 24px rgba(10,49,58,.07)}.kb-stat{font-size:1.8rem;font-weight:800;color:#073b45}.kb-status{font-size:.7rem}.kb-answer{max-width:480px;color:#64777e}.kb-actions{display:flex;gap:6px;justify-content:flex-end}.kb-actions form{margin:0}</style>
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><h1 class="h3 mb-1">Quản lý kiến thức AI</h1><p class="text-muted mb-0">Admin cập nhật nội dung, hệ thống tự chia chunk, tạo embedding và đưa vào RAG.</p></div><a class="btn btn-success" href="{{ route('admin.knowledge-base.create') }}"><i class="bi bi-plus-lg me-1"></i>Thêm kiến thức</a></div>
<div class="row g-3 mb-4">@foreach(['Tổng kiến thức'=>$stats['total'],'Đang hoạt động'=>$stats['active'],'Đã đồng bộ'=>$stats['synced'],'Lỗi đồng bộ'=>$stats['failed']] as $label=>$value)<div class="col-6 col-xl-3"><div class="card kb-card h-100"><div class="card-body"><small class="text-muted">{{ $label }}</small><div class="kb-stat">{{ $value }}</div></div></div></div>@endforeach</div>
<div class="card kb-card mb-4"><div class="card-body"><form class="row g-2"><div class="col-lg-6"><input class="form-control" name="search" value="{{ request('search') }}" placeholder="Tìm tiêu đề hoặc nội dung..."></div><div class="col-lg-3"><select class="form-select" name="category"><option value="">Mọi danh mục</option>@foreach($categories as $key=>$label)<option value="{{ $key }}" @selected(request('category')===$key)>{{ $label }}</option>@endforeach</select></div><div class="col-lg-2"><select class="form-select" name="sync_status"><option value="">Mọi trạng thái</option>@foreach(['PENDING','SYNCED','FAILED'] as $status)<option @selected(request('sync_status')===$status)>{{ $status }}</option>@endforeach</select></div><div class="col-lg-1"><button class="btn btn-dark w-100"><i class="bi bi-search"></i></button></div></form></div></div>
<div class="card kb-card"><div class="card-body"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Kiến thức</th><th>Danh mục</th><th>Chunk</th><th>Đồng bộ</th><th>Cập nhật</th><th></th></tr></thead><tbody>@forelse($items as $item)<tr><td><strong>{{ $item->title ?: $item->intent }}</strong><div class="kb-answer small">{{ Str::limit($item->answer,130) }}</div>@if(!$item->active)<span class="badge text-bg-secondary mt-1">Đã tắt</span>@endif</td><td>{{ $categories[$item->category] ?? $item->category }}</td><td>{{ $item->documents_count }}</td><td><span class="badge kb-status {{ $item->sync_status==='SYNCED'?'text-bg-success':($item->sync_status==='FAILED'?'text-bg-danger':'text-bg-warning') }}">{{ $item->sync_status }}</span>@if($item->sync_error)<div class="small text-danger mt-1" title="{{ $item->sync_error }}">{{ Str::limit($item->sync_error,60) }}</div>@endif</td><td><small>{{ $item->updated_at->format('d/m/Y H:i') }}<br>{{ $item->editor?->name }}</small></td><td><div class="kb-actions"><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.knowledge-base.edit',$item) }}" title="Sửa"><i class="bi bi-pencil"></i></a><form method="POST" action="{{ route('admin.knowledge-base.sync',$item) }}">@csrf<button class="btn btn-sm btn-outline-success" title="Tạo lại embedding"><i class="bi bi-arrow-repeat"></i></button></form><form method="POST" action="{{ route('admin.knowledge-base.toggle',$item) }}">@csrf<button class="btn btn-sm btn-outline-secondary" title="{{ $item->active?'Tắt':'Bật' }}"><i class="bi {{ $item->active?'bi-eye-slash':'bi-eye' }}"></i></button></form><form method="POST" action="{{ route('admin.knowledge-base.destroy',$item) }}" onsubmit="return confirm('Xóa kiến thức và toàn bộ vector liên quan?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger" title="Xóa"><i class="bi bi-trash"></i></button></form></div></td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-5">Chưa có kiến thức nào.</td></tr>@endforelse</tbody></table></div><div class="mt-3">{{ $items->links() }}</div></div></div>
@endsection
