@extends('layouts.app')

@section('title', 'Giới thiệu - SmashZone')

@push('styles')
<style>
    .about-page{max-width:1180px;margin:34px auto 0}.about-hero{display:grid;grid-template-columns:1.2fr .8fr;gap:36px;align-items:center;padding:52px;border-radius:24px;color:#fff;background:linear-gradient(125deg,#082536,#087c42)}.about-hero__tag{display:inline-block;margin-bottom:14px;color:#a7f3c7;font-size:12px;font-weight:800;letter-spacing:.1em}.about-hero h1{margin:0 0 16px;font-size:clamp(31px,4.5vw,50px);line-height:1.15;font-weight:800}.about-hero p{max-width:620px;margin:0;color:rgba(255,255,255,.85);font-size:16px;line-height:1.75}.about-hero__mark{display:grid;width:180px;height:180px;place-items:center;justify-self:end;border:1px solid rgba(255,255,255,.25);border-radius:50%;background:rgba(255,255,255,.1);font-size:76px}.about-section{margin-top:54px}.about-section__head{max-width:680px;margin-bottom:22px}.about-section__head span{color:#087c42;font-size:12px;font-weight:800;letter-spacing:.08em}.about-section__head h2{margin:8px 0;font-size:28px;font-weight:800}.about-section__head p{margin:0;color:#58708b;line-height:1.7}.about-values{display:grid;grid-template-columns:repeat(4,1fr);gap:18px}.about-value{padding:23px;border:1px solid #dbe8df;border-radius:18px;background:#fff}.about-value i{display:grid;width:44px;height:44px;place-items:center;border-radius:12px;background:#e8f9ee;color:#087c42;font-size:21px}.about-value h3{margin:16px 0 7px;font-size:17px;font-weight:800}.about-value p{margin:0;color:#60727a;font-size:13px;line-height:1.6}.about-cta{display:flex;align-items:center;justify-content:space-between;gap:24px;margin-top:54px;padding:30px 34px;border-radius:20px;background:#e9f8ee}.about-cta h2{margin:0 0 6px;font-size:24px;font-weight:800}.about-cta p{margin:0;color:#58708b}@media(max-width:850px){.about-hero{grid-template-columns:1fr}.about-hero__mark{display:none}.about-values{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.about-page{margin-top:16px}.about-hero{padding:32px 24px}.about-values{grid-template-columns:1fr}.about-cta{align-items:start;flex-direction:column;padding:26px 22px}}
</style>
@endpush

@section('content')
<section class="about-page">
    <div class="about-hero"><div><span class="about-hero__tag">VỀ SMASHZONE</span><h1>Đặt sân dễ dàng.<br>Sẵn sàng vào trận.</h1><p>SmashZone là nền tảng giúp người chơi cầu lông tìm sân, xem lịch trống và đặt sân nhanh chóng. Chúng tôi hướng đến một trải nghiệm rõ ràng, tiện lợi cho mỗi trận đấu.</p></div><div class="about-hero__mark"><i class="bi bi-lightning-charge-fill"></i></div></div>
    <section class="about-section"><div class="about-section__head"><span>TRẢI NGHIỆM</span><h2>Mọi thứ bạn cần để ra sân</h2><p>Từ việc chọn sân đến quản lý lịch đặt, SmashZone giúp bạn chủ động hơn trong từng lần chơi.</p></div><div class="about-values"><article class="about-value"><i class="bi bi-lightning-charge"></i><h3>Đặt sân nhanh</h3><p>Chọn sân và khung giờ yêu thích chỉ trong vài bước đơn giản.</p></article><article class="about-value"><i class="bi bi-clock-history"></i><h3>Lịch trống rõ ràng</h3><p>Cập nhật tình trạng sân để bạn dễ dàng chọn thời điểm phù hợp.</p></article><article class="about-value"><i class="bi bi-shield-check"></i><h3>Thông tin minh bạch</h3><p>Giá thuê, trạng thái đặt sân và ưu đãi luôn được hiển thị rõ ràng.</p></article><article class="about-value"><i class="bi bi-calendar2-check"></i><h3>Quản lý tiện lợi</h3><p>Theo dõi lịch đặt và thông tin tài khoản ở cùng một nơi.</p></article></div></section>
    <section class="about-cta"><div><h2>Sẵn sàng cho trận đấu tiếp theo?</h2><p>Khám phá sân cầu lông và đặt lịch ngay hôm nay.</p></div><a class="sc-btn-pill sc-btn-primary" href="{{ route('courts.index') }}">Tìm sân ngay <i class="bi bi-arrow-right"></i></a></section>
</section>
@endsection
