@extends('layouts.admin')
@section('page_heading','Quản lý sự cố sân')
@section('content')<x-admin.workspace>
@include('partials.incident-ui')
<a class="sz-action mb-3" href="{{ route('incident-tickets.index') }}">Sự cố & Khiếu nại từ khách</a>
<a href="{{ route('admin.incidents.bulk') }}" class="sz-action sz-action--danger mb-3"><i class="bi bi-calendar-x" aria-hidden="true"></i>Xử lý sự cố sân</a>
<a href="{{ route('special-refunds.index') }}" class="sz-action mb-3"><i class="bi bi-wallet2" aria-hidden="true"></i>Hoàn tiền chờ xử lý</a>
<div class="card border-0 shadow-sm table-responsive"><table class="table mb-0"><thead><tr><th>Mã</th><th>Sân / người báo</th><th>Nội dung</th><th>Mức độ</th><th>Trạng thái</th><th>Xử lý</th></tr></thead><tbody>@foreach($incidents as $incident)<tr><td>{{ $incident->incident_code }}</td><td>{{ $incident->court->name }}<br><small>{{ $incident->reporter->name }}</small></td><td><strong>{{ $incident->type }}</strong><br>{{ Str::limit($incident->description,80) }}</td><td>{{ $incident->severity }}</td><td><span class="badge bg-light text-dark">{{ $incident->status }}</span></td><td class="sz-table-actions"><x-admin.row-actions><form method="POST" action="{{ route('admin.incidents.update',$incident) }}">@csrf @method('PUT')<select aria-label="Trạng thái xử lý" name="status" class="form-select form-select-sm mb-1">@foreach(['OPEN','IN_PROGRESS','RESOLVED','CLOSED'] as $s)<option @selected($incident->status===$s)>{{ $s }}</option>@endforeach</select><input aria-label="Ghi chú xử lý" name="resolution_note" value="{{ $incident->resolution_note }}" class="form-control form-control-sm mb-1" placeholder="Ghi chú xử lý"><button class="sz-action sz-action--primary sz-action--small">Lưu</button></form></x-admin.row-actions></td></tr>@endforeach</tbody></table></div><div class="mt-3"><x-admin.pagination :rows="$incidents" /></div>
</x-admin.workspace>@endsection
